apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-template
  labels:
    env: pp
spec:
  selector:
    matchLabels:
      run: aplicacao-template
  replicas: 1
  template:
    metadata:
      labels:
        run: aplicacao-template
    spec:
      containers:
        - name: aplicacao-template
          image: 10.90.0.30:8123/confidence/aplicacao-template/pp:latest
          volumeMounts:
            - mountPath: /mnt/
              name: mnt
            - mountPath: /logs/
              name: logs
          ports:
            - name: http
              containerPort: 8150
          resources:
            limits:
              memory: "2048Mi"
      imagePullPolicy: Always
      imagePullSecrets:
        - name: dockernexus
      volumes:
        - name: mnt
          hostPath:
            path: /mnt/
            type: Directory
        - name: logs
          hostPath:
            path: /logs/
            type: Directory
------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: aplicacao-template
  labels:
    run: aplicacao-template
spec:
  type: LoadBalancer
  externalIPs:
    - 10.90.0.12
  ports:
    - port: 8150
      protocol: TCP
  selector:
    run: aplicacao-template